const PARTIES={
  Labour:{key:'labour',color:'#d7263d'}, Conservative:{key:'conservative',color:'#2d82c7'}, 'Liberal Democrats':{key:'libdem',color:'#f28e2b'}, SNP:{key:'snp',color:'#f4c430'}, Reform:{key:'reform',color:'#33b8b2'}, Green:{key:'green',color:'#0aa37f'}, Other:{key:'other',color:'#8c949c'}
};
const DEFAULT_STATE={
  currentView:'dashboard', dark:false, week:0, date:'2024-11-11', electionWeeks:25,
  pm:{name:'Eleanor Ashford',party:'Labour',approval:34,approvalDelta:-2,politicalCapital:62,trust:46,unity:71},
  economy:{gdp:1.1,inflation:2.8,unemployment:4.4,deficit:-12.4,debt:97.2,wages:3.0},
  seats:{Labour:372,Conservative:178,'Liberal Democrats':52,SNP:22,Reform:14,Green:4,Other:8},
  polling:{Labour:34,Conservative:31,'Liberal Democrats':14,Reform:11,Green:6,SNP:4},
  cabinet:[
    ['James Calder','Chancellor of the Exchequer','HM Treasury',82,'Loyal'],['Priya Desai','Home Secretary','Home Office',76,'Loyal'],['Oliver Grant','Foreign Secretary','Foreign Office',69,'Loyal'],['Sophie Mitchell','Health Secretary','Health & Social Care',63,'Loyal'],['Marcus Bell','Energy Secretary','Energy Security & Net Zero',51,'Caution'],['Lena Okafor','Education Secretary','Education',46,'Caution']
  ],
  bills:[
    ['Growth and Investment Bill','Committee',4,6],['Renters’ Reform Bill','Second Reading',2,6],['Border Security Bill','Committee',3,6],['NHS Reform Bill','Report',5,6],['Clean Energy Transition Bill','Third Reading',5,6],['Digital Markets Bill','Committee',3,6]
  ],
  events:[
    ['Government','Cabinet dissent over tax policy','Senior ministers reportedly unconvinced.'],['Health','Hospital waiting list figures worsen','Pressure grows ahead of winter.'],['Economy','Business groups urge faster reform','CBI calls for planning changes.'],['Parliament','Backbench rebellion threatens bill','Up to 30 MPs expected to abstain.'],['Media','Positive coverage on green energy','Major investment plan welcomed.']
  ],
  history:[], election:null, declarations:[], media:[], crises:[], lastEventWeek:-2
};
let state=load();
function load(){try{return Object.assign(structuredClone(DEFAULT_STATE),JSON.parse(localStorage.getItem('mandateState')||'{}'));}catch{return structuredClone(DEFAULT_STATE)}}
function save(){localStorage.setItem('mandateState',JSON.stringify(state))}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmtDate=d=>new Date(d+'T12:00:00').toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short',year:'numeric'});
function addWeeks(date,weeks){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+weeks*7);return d.toISOString().slice(0,10)}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function toast(title,msg=''){const el=document.createElement('div');el.className='toast';el.innerHTML=`<strong>${title}</strong><span class="subtle">${msg}</span>`;$('#toastRoot').append(el);setTimeout(()=>el.remove(),4200)}
function modal(title,html,footer=''){$('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>${title}</h2><button class="close-x" onclick="closeModal()">×</button></div><div class="modal-body">${html}</div>${footer?`<div class="modal-foot">${footer}</div>`:''}</div></div>`}
window.closeModal=()=>$('#modalRoot').innerHTML='';
const navItems=[['dashboard','▣','Dashboard'],['government','♜','Government'],['parliament','♙','Parliament'],['laws','▤','Laws & Policy'],['elections','▣','Elections'],['opinion','♡','Public Opinion'],['media','▧','Media'],['events','◇','Events'],['intelligence','⌂','Intelligence'],['settings','⚙','Settings'],['help','?','Help & Guide']];
function renderNav(){const n=$('#nav');n.innerHTML=navItems.map(([id,ic,l])=>`<button class="nav-btn ${state.currentView===id?'active':''}" data-view="${id}"><span class="nav-icon">${ic}</span><span>${l}</span></button>`).join('');n.onclick=e=>{const b=e.target.closest('.nav-btn');if(!b)return;state.currentView=b.dataset.view;save();render()}}
function renderTop(){document.body.classList.toggle('dark',!!state.dark);$('#pmName').textContent=state.pm.name;$('#pmParty').textContent=state.pm.party;$('#topApproval').textContent=state.pm.approval+'%';$('#topApprovalDelta').textContent=(state.pm.approvalDelta>=0?'▲ ':'▼ ')+Math.abs(state.pm.approvalDelta);$('#topGovStatus').textContent=getGovStatus();$('#topMajority').textContent=`${state.pm.party} ${state.seats[state.pm.party]||0} / 650`;$('#budgetPos').textContent=(state.economy.deficit>=0?'£':'-£')+Math.abs(state.economy.deficit).toFixed(1)+'bn';$('#gameDate').textContent=fmtDate(state.date);$('#gameWeek').textContent=`Year ${Math.floor(state.week/52)+1}, Week ${state.week%52+1}`;$('#nextPmqs').textContent=fmtDate(addWeeks(state.date,1)).replace(/^[A-Za-z]{3}, /,'Wed, ')}
function getGovStatus(){const s=state.seats[state.pm.party]||0;return s>=326?'Majority Government':s>=300?'Minority Government':'Coalition / Minority'}
function sectionTitle(title,sub=''){return `<div class="section-title"><div><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div><div class="toolbar"><button class="ghost-btn" onclick="toggleTheme()">${state.dark?'☀ Light':'◐ Dark'}</button><button class="btn primary" onclick="advanceWeek()">Advance Week</button></div></div>`}
function render(){renderNav();renderTop();const fn=views[state.currentView]||views.dashboard;$('#view').innerHTML=fn();wireView();}
function wireView(){const c=$('#view');c?.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>actions[b.dataset.act]?.(b.dataset));}
window.toggleTheme=()=>{state.dark=!state.dark;save();render()};
window.advanceWeek=advanceWeek;
$('#advanceDayBtn').onclick=advanceWeek;
$('#resetBtn').onclick=()=>{if(confirm('Reset the simulation to its starting state?')){state=structuredClone(DEFAULT_STATE);save();render()}};
function advanceWeek(){state.week++;state.date=addWeeks(state.date,1);state.electionWeeks=Math.max(0,state.electionWeeks-1);tickEconomy();tickPolitics();maybeEvent();if(state.electionWeeks===0&&!state.election)startElectionNight();save();render();}
function tickEconomy(){state.economy.gdp=+(state.economy.gdp+(Math.random()-.5)*.3).toFixed(1);state.economy.inflation=clamp(+(state.economy.inflation+(Math.random()-.5)*.25).toFixed(1),.2,12);state.economy.unemployment=clamp(+(state.economy.unemployment+(Math.random()-.5)*.12).toFixed(1),2,12);state.economy.deficit=+(state.economy.deficit+(Math.random()-.53)*1.2).toFixed(1)}
function tickPolitics(){const shock=(Math.random()-.5)*4;state.pm.approvalDelta=Math.round(shock);state.pm.approval=clamp(Math.round(state.pm.approval+shock),8,78);state.pm.trust=clamp(Math.round(state.pm.trust+shock/2),10,80);state.pm.unity=clamp(Math.round(state.pm.unity+(Math.random()-.5)*3),15,95);Object.keys(state.polling).forEach(p=>state.polling[p]=clamp(Math.round(state.polling[p]+(Math.random()-.5)*2),2,55));}
function maybeEvent(){if(state.week-state.lastEventWeek<1||Math.random()<.45)return;state.lastEventWeek=state.week;const pool=[
  ['Parliament','Backbench rebellion grows','A group of MPs has signed a letter demanding changes to a flagship bill.',-2],['Government','Junior minister resigns','A minister has resigned citing personal reasons.',-1],['Media','Leak dominates front pages','Internal government messages have appeared in the press.',-3],['Economy','Growth forecast upgraded','Forecasters have raised expectations for the next quarter.',2],['Public','Hospital waiting times fall','New figures show an improvement in waiting times.',2],['Parliament','MP defects to another party','A sitting MP has crossed the floor, changing the parliamentary arithmetic.',-1],['Election','By-election called','A constituency will vote after an MP resignation.',0],['International','Diplomatic dispute escalates','The government faces pressure to respond to a fast-moving overseas dispute.',-2]
];const ev=pool[Math.floor(Math.random()*pool.length)];state.events.unshift([ev[0],ev[1],ev[2]]);state.events=state.events.slice(0,12);state.pm.approval=clamp(state.pm.approval+ev[3],8,78);state.history.unshift({date:state.date,title:ev[1],detail:ev[2]});toast(ev[1],ev[2]);}
function dashboard(){return sectionTitle('Dashboard','Your premiership at a glance — politics, policy, opinion and the road to the next election.')+`<div class="grid dashboard-grid">
<div class="card"><div class="card-header"><div><h2>United Kingdom</h2><div class="subtle">Constituency Control</div></div><span class="badge">2024</span></div><div class="card-body map-wrap"><img src="uk-map.svg" alt="stylised UK political map"><div class="legend">${partyLegend()}</div></div></div>
<div class="card"><div class="card-header"><h2>Premiership Timeline</h2><span class="subtle">Year ${Math.floor(state.week/52)+1} of 5</span></div><div class="card-body">${timeline()}</div><div class="card-header"><h2>Cabinet</h2><button class="ghost-btn" data-act="cabinet">View All</button></div><div class="card-body">${cabinetTable(6)}</div></div>
<div class="card"><div class="card-header"><h2>Legislation Tracker</h2><button class="ghost-btn" data-act="laws">View All</button></div><div class="card-body">${billTable()}</div></div>
<div class="card"><div class="card-header"><h2>Public Opinion</h2><button class="ghost-btn" data-act="opinion">View Details</button></div><div class="card-body">${approvalChart()}</div></div>
<div class="card"><div class="card-header"><h2>Constituency Declarations</h2><span class="badge bad">● Live</span></div><div class="card-body">${declarationTable()}</div></div>
<div class="card"><div class="card-header"><h2>Events & Pressure on the PM</h2><button class="ghost-btn" data-act="events">View All</button></div><div class="card-body event-list">${eventList(5)}</div></div>
<div class="card span-3">${electionPanel()}</div></div>`}
function partyLegend(){return Object.entries(state.seats).map(([p,n])=>`<div class="legend-row"><span><i class="dot ${PARTIES[p]?.key||'other'}"></i>${p}</span><strong>${n}</strong></div>`).join('')}
function timeline(){const labels=['General Election','Government Formed','King’s Speech','Autumn Budget','Local Elections','Next General Election'];return `<div class="timeline">${labels.map((l,i)=>`<div class="milestone ${i<Math.min(3,1+Math.floor(state.week/10))?'done':''}"><strong>${l}</strong><div class="subtle">${i===5?'May 2029':i<3?'Jul 2024':i===3?'Oct 2024':'May 2025'}</div></div>`).join('')}</div>`}
function cabinetTable(limit=99){return `<table class="table"><thead><tr><th>Minister</th><th>Department</th><th>Loyalty</th><th>Status</th></tr></thead><tbody>${state.cabinet.slice(0,limit).map(m=>`<tr><td><strong>${m[0]}</strong><br><span class="subtle">${m[1]}</span></td><td>${m[2]}</td><td><div class="progress"><i style="width:${m[3]}%"></i></div><span class="subtle">${m[3]}%</span></td><td><span class="badge ${m[4]==='Loyal'?'good':'warn'}">${m[4]}</span></td></tr>`).join('')}</tbody></table>`}
function billTable(){return `<table class="table"><thead><tr><th>Bill</th><th>Stage</th><th>Progress</th></tr></thead><tbody>${state.bills.map(b=>`<tr><td>${b[0]}</td><td>${b[1]}</td><td><div class="progress"><i style="width:${(b[2]/b[3])*100}%"></i></div><span class="subtle">${b[2]}/${b[3]}</span></td></tr>`).join('')}</tbody></table>`}
function approvalChart(){return `<div class="toolbar"><span class="badge">Approval Rating</span><span class="badge">Voting Intention</span><span class="badge">Key Issues</span></div><div class="chart"><div class="spark"><svg viewBox="0 0 400 150" preserveAspectRatio="none"><polyline points="0,75 40,70 80,78 120,65 160,84 200,88 240,101 280,95 320,110 360,107 400,${150-state.pm.approval*1.5}"/><polyline class="blue-line" points="0,105 40,100 80,85 120,72 160,65 200,70 240,58 280,53 320,48 360,52 400,49"/></svg></div></div><div class="toolbar"><strong style="color:var(--accent)">${state.pm.approval}% Approval</strong><strong style="color:var(--blue)">${state.pm.trust}% Trust</strong></div>`}
function declarationTable(){const rows=state.declarations.length?state.declarations.slice(-6).reverse():[['Northfield','Labour HOLD','22:41'],['Rivermere','Conservative GAIN from Labour','22:38'],['Eastborough','Labour HOLD','22:36'],['Kingswood','Liberal Democrat GAIN','22:33'],['Seaton','Conservative HOLD','22:31'],['Brampton','Labour GAIN','22:28']];return `<table class="table"><thead><tr><th>Constituency</th><th>Result</th><th>Time</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</tbody></table>`}
function eventList(limit=8){return state.events.slice(0,limit).map(e=>`<div class="event"><div class="event-icon">◆</div><div><strong>${e[1]}</strong><small>${e[2]}</small></div><span class="badge">${e[0]}</span></div>`).join('')}
function electionPanel(){const election=state.election;const declared=election?.declared||398;const pct=Math.round(declared/650*100);const seats=election?.liveSeats||{Labour:212,Conservative:141,'Liberal Democrats':28,Reform:8,SNP:6,Green:1,Other:4};return `<div class="election-banner"><div><strong style="font:24px Georgia,serif">▥ Election Night</strong> <span>Live results as they come in across the UK</span></div><div>${declared} / 650 declared · ${pct}%</div></div><div class="election-grid"><div><h3>Exit Poll</h3><div class="subtle">Based on 22,000 interviews</div><div class="exit-cards">${Object.entries(election?.exitPoll||{Labour:290,Conservative:240,'Liberal Democrats':66,Reform:22,SNP:20,Other:12}).map(([p,n])=>`<div class="exit-card"><span>${p}</span><strong>${n}</strong><small class="subtle">${PARTIES[p]?.key||''}</small></div>`).join('')}</div></div><div><h3>Seats (Live)</h3><div class="seat-bars">${Object.entries(seats).map(([p,n])=>`<div class="seat-row"><span>${p}</span><div class="bar"><i style="width:${Math.min(100,n/4)}%;background:${PARTIES[p]?.color||'#999'}"></i></div><strong>${n}</strong></div>`).join('')}</div><div class="subtle" style="margin-top:8px">326 for a majority</div></div><div><h3>Election Controls</h3><div class="controls"><button class="btn" data-act="pauseElection">Ⅱ Pause</button><button class="btn primary" data-act="normalElection">▶ Normal</button><button class="btn" data-act="fastElection">≫ Fast</button><button class="btn" data-act="ultraElection">≫ Ultra</button></div><button class="danger-btn full" style="margin-top:10px" data-act="finishElection">⚑ Finish Election</button><div class="subtle" style="margin-top:8px">${state.electionWeeks} weeks to the next scheduled election</div></div></div>`}
function government(){return sectionTitle('Government','Cabinet, departments, political capital and internal stability.')+`<div class="kpi-grid"><div class="card kpi"><span>Political Capital</span><strong>${state.pm.politicalCapital}</strong></div><div class="card kpi"><span>Party Unity</span><strong>${state.pm.unity}%</strong></div><div class="card kpi"><span>Public Trust</span><strong>${state.pm.trust}%</strong></div><div class="card kpi"><span>Approval</span><strong>${state.pm.approval}%</strong></div></div><div class="two-col" style="margin-top:12px"><div class="card"><div class="card-header"><h2>Cabinet</h2><button class="btn primary" data-act="reshuffle">Reshuffle</button></div><div class="card-body">${cabinetTable()}</div></div><div class="card"><div class="card-header"><h2>Government Priorities</h2></div><div class="card-body list">${['Economic growth','NHS waiting times','Housing supply','Border management','Energy security'].map((x,i)=>`<div class="list-row"><span>${x}</span><span class="badge ${i<2?'warn':'good'}">${i<2?'At risk':'On track'}</span></div>`).join('')}</div></div></div>`}
function parliament(){return sectionTitle('Parliament','650-seat chamber, government arithmetic, rebellions and votes.')+`<div class="kpi-grid">${Object.entries(state.seats).slice(0,4).map(([p,n])=>`<div class="card kpi"><span>${p}</span><strong>${n}</strong></div>`).join('')}</div><div class="two-col" style="margin-top:12px"><div class="card"><div class="card-header"><h2>Seat Distribution</h2></div><div class="card-body">${Object.entries(state.seats).map(([p,n])=>`<div class="seat-row"><span>${p}</span><div class="bar"><i style="width:${n/6.5}%;background:${PARTIES[p]?.color||'#999'}"></i></div><strong>${n}</strong></div>`).join('')}</div></div><div class="card"><div class="card-header"><h2>Parliamentary Actions</h2></div><div class="card-body controls"><button class="btn" data-act="confidence">Confidence Vote</button><button class="btn" data-act="pmqs">Run PMQs</button><button class="btn" data-act="rebellion">Trigger Rebellion</button><button class="btn" data-act="byelection">Call By-election</button></div></div></div>`}
function laws(){return sectionTitle('Laws & Policy','Draft bills, move legislation through Parliament, and track political cost.')+`<div class="two-col"><div class="card"><div class="card-header"><h2>Legislation</h2><button class="btn primary" data-act="newBill">New Bill</button></div><div class="card-body">${billTable()}</div></div><div class="card"><div class="card-header"><h2>Policy Effects</h2></div><div class="card-body list"><div class="list-row"><span>Fiscal headroom</span><strong>£${Math.max(0,18+state.economy.deficit).toFixed(1)}bn</strong></div><div class="list-row"><span>Business confidence</span><strong>${clamp(50+Math.round(state.economy.gdp*8),10,90)}%</strong></div><div class="list-row"><span>Public trust</span><strong>${state.pm.trust}%</strong></div><div class="list-row"><span>Backbench support</span><strong>${state.pm.unity}%</strong></div></div></div></div>`}
function elections(){return sectionTitle('Elections','25-week campaign mode, live polling and full election-night simulation.')+`<div class="kpi-grid"><div class="card kpi"><span>Weeks to Election</span><strong>${state.electionWeeks}</strong></div><div class="card kpi"><span>Campaign Momentum</span><strong>${clamp(state.pm.approval+10,0,100)}</strong></div><div class="card kpi"><span>Party Polling</span><strong>${state.polling[state.pm.party]||0}%</strong></div><div class="card kpi"><span>Target Seats</span><strong>${Math.max(12,Math.round((326-(state.seats[state.pm.party]||0))/2+20))}</strong></div></div><div class="card" style="margin-top:12px"><div class="card-header"><h2>Campaign Timeline</h2><button class="btn primary" data-act="campaignAction">Campaign Action</button></div><div class="card-body">${campaignTimeline()}</div></div><div class="card" style="margin-top:12px">${electionPanel()}</div>`}
function campaignTimeline(){const w=state.electionWeeks;const ms=[25,20,16,12,8,6,4,2,1,0];return `<div class="timeline">${ms.slice(0,6).map((m,i)=>`<div class="milestone ${w<=m?'done':''}"><strong>${m===0?'Election Day':m+' weeks'}</strong><div class="subtle">${['Campaign begins','Launch events','Policy week','Manifesto prep','Manifesto launch','TV debate'][i]}</div></div>`).join('')}</div><div class="list" style="margin-top:18px">${['Campaign visit','Policy announcement','Media interview','Debate preparation','Target-seat blitz'].map(x=>`<div class="list-row"><span>${x}</span><button class="ghost-btn" data-act="campaignAction">Run</button></div>`).join('')}</div>`}
function opinion(){return sectionTitle('Public Opinion','Polling, approval, trust and issue salience.')+`<div class="two-col"><div class="card"><div class="card-header"><h2>Voting Intention</h2></div><div class="card-body seat-bars">${Object.entries(state.polling).map(([p,n])=>`<div class="seat-row"><span>${p}</span><div class="bar"><i style="width:${n*2}%;background:${PARTIES[p]?.color||'#999'}"></i></div><strong>${n}%</strong></div>`).join('')}</div></div><div class="card"><div class="card-header"><h2>Leadership</h2></div><div class="card-body">${approvalChart()}<div class="list" style="margin-top:12px"><div class="list-row"><span>Approval</span><strong>${state.pm.approval}%</strong></div><div class="list-row"><span>Trust</span><strong>${state.pm.trust}%</strong></div><div class="list-row"><span>Party Unity</span><strong>${state.pm.unity}%</strong></div></div></div></div></div>`}
function media(){return sectionTitle('Media','Headlines, interviews, leaks and the national news cycle.')+`<div class="two-col"><div class="card"><div class="card-header"><h2>Live Media Cycle</h2><button class="btn primary" data-act="pressConference">Press Conference</button></div><div class="card-body event-list">${eventList(9)}</div></div><div class="card"><div class="card-header"><h2>Media Strategy</h2></div><div class="card-body list">${['Prime-time interview','Regional broadcast','Sunday paper op-ed','Policy explainer','Rapid rebuttal'].map(x=>`<div class="list-row"><span>${x}</span><button class="ghost-btn" data-act="mediaAction">Deploy</button></div>`).join('')}</div></div></div>`}
function events(){return sectionTitle('Events','Random events, crises and pressure on the government.')+`<div class="two-col"><div class="card"><div class="card-header"><h2>Live Events</h2><button class="btn primary" data-act="randomEvent">Generate Event</button></div><div class="card-body event-list">${eventList(12)}</div></div><div class="card"><div class="card-header"><h2>Crisis Room</h2></div><div class="card-body list">${['Flooding emergency','Cyber incident','Transport strike','Energy supply concern','International crisis'].map((x,i)=>`<div class="list-row"><span>${x}</span><span class="badge ${i<2?'bad':'warn'}">${i<2?'High':'Watch'}</span></div>`).join('')}</div></div></div>`}
function intelligence(){return sectionTitle('Intelligence','Internal signals, political risk and forward-looking warnings.')+`<div class="three-col"><div class="card kpi"><span>Leadership Risk</span><strong>${state.pm.unity<45?'HIGH':'LOW'}</strong></div><div class="card kpi"><span>Rebellion Risk</span><strong>${100-state.pm.unity}%</strong></div><div class="card kpi"><span>Election Risk</span><strong>${Math.max(0,(state.polling.Conservative||0)-(state.polling[state.pm.party]||0)+50)}%</strong></div></div><div class="card" style="margin-top:12px"><div class="card-header"><h2>Private Briefing</h2></div><div class="card-body list"><div class="list-row"><span>Whips report</span><strong>${state.pm.unity}% supportive</strong></div><div class="list-row"><span>Cabinet stability</span><strong>${Math.round(state.cabinet.reduce((a,b)=>a+b[3],0)/state.cabinet.length)}%</strong></div><div class="list-row"><span>Economic risk</span><strong>${state.economy.gdp<0?'Elevated':'Manageable'}</strong></div><div class="list-row"><span>Media pressure</span><strong>${state.pm.approval<30?'Severe':'Moderate'}</strong></div></div></div>`}
function settings(){return sectionTitle('Settings','Visuals, simulation pace and save controls.')+`<div class="two-col"><div class="card"><div class="card-header"><h2>Appearance</h2></div><div class="card-body list"><div class="list-row"><span>Dark Mode</span><button class="btn" onclick="toggleTheme()">${state.dark?'Disable':'Enable'}</button></div><div class="list-row"><span>Theme</span><span class="badge">Westminster Analyst</span></div></div></div><div class="card"><div class="card-header"><h2>Simulation</h2></div><div class="card-body controls"><button class="btn" onclick="save();toast('Game saved','Stored locally in this browser.')">Save Game</button><button class="danger-btn" onclick="if(confirm('Reset all progress?')){state=structuredClone(DEFAULT_STATE);save();render()}">Reset</button></div></div></div>`}
function help(){return sectionTitle('Help & Guide','How the upgraded MANDATE simulation works.')+`<div class="card"><div class="card-body"><h2>Core loop</h2><p>Advance the simulation week by week. Public opinion, the economy, cabinet loyalty and party unity all evolve. Random events can trigger resignations, rebellions, scandals, crises, by-elections and polling shocks.</p><h2>Election mode</h2><p>The campaign runs down from 25 weeks. When Election Day arrives, the election-night engine generates an exit poll and then declares constituencies over time. You can pause, speed up, or finish instantly.</p><h2>Government survival</h2><p>Low party unity increases the risk of rebellions and leadership pressure. Approval and trust influence campaign momentum. Bills and media actions can improve or damage your position.</p><h2>Dark mode</h2><p>Use the Dark button in any section or Settings. The choice is saved automatically.</p></div></div>`}
const views={dashboard,government,parliament,laws,elections,opinion,media,events,intelligence,settings,help};
const actions={
  cabinet:()=>{state.currentView='government';save();render()},laws:()=>{state.currentView='laws';save();render()},opinion:()=>{state.currentView='opinion';save();render()},events:()=>{state.currentView='events';save();render()},
  reshuffle:()=>modal('Cabinet Reshuffle',`<p>Choose a minister to replace. This demo reshuffle automatically appoints a new fictional minister and slightly improves cabinet loyalty.</p>${state.cabinet.map((m,i)=>`<button class="ghost-btn" style="margin:4px" onclick="reshuffle(${i})">Replace ${m[0]}</button>`).join('')}`),
  confidence:()=>{const yes=Math.round(300+state.pm.unity*1.6+Math.random()*40);const passed=yes>=326;modal('Confidence Vote',`<h2>${passed?'Government survives':'Government defeated'}</h2><p>${yes} MPs backed the government; ${650-yes} opposed.</p>`);if(!passed){state.pm.approval-=5;state.electionWeeks=Math.min(state.electionWeeks,6)}save();renderTop()},
  pmqs:()=>{const gain=Math.random()<.55?2:-2;state.pm.approval=clamp(state.pm.approval+gain,8,78);toast('PMQs complete',gain>0?'Strong performance — approval rises.':'Difficult session — approval falls.');save();render()},
  rebellion:()=>{state.pm.unity=clamp(state.pm.unity-8,10,95);state.events.unshift(['Parliament','Backbench rebellion erupts','A significant bloc of government MPs threatens to vote against the whip.']);toast('Backbench rebellion','Party unity has fallen.');save();render()},
  byelection:()=>{state.events.unshift(['Election','By-election called','A seat has become vacant and a by-election will take place.']);toast('By-election called');save();render()},
  newBill:()=>modal('Draft New Bill',`<div class="form-grid"><div class="field"><label>Bill name</label><input id="billName" value="Public Services Reform Bill"></div><div class="field"><label>Policy area</label><select id="billArea"><option>Economy</option><option>Health</option><option>Education</option><option>Justice</option><option>Energy</option></select></div><div class="field"><label>Political cost</label><select id="billCost"><option value="2">Low</option><option value="5">Medium</option><option value="9">High</option></select></div></div>`,`<button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="createBill()">Create Bill</button>`),
  campaignAction:()=>{const gain=Math.random()<.65?1:-1;state.pm.approval=clamp(state.pm.approval+gain,8,78);state.polling[state.pm.party]=clamp((state.polling[state.pm.party]||0)+gain,2,55);toast('Campaign action complete',gain>0?'Momentum improved.':'The event did not land well.');save();render()},
  pressConference:()=>{const gain=Math.random()<.6?2:-2;state.pm.approval=clamp(state.pm.approval+gain,8,78);toast('Press conference finished',gain>0?'Coverage is broadly positive.':'Difficult questions dominate coverage.');save();render()},
  mediaAction:()=>{state.pm.trust=clamp(state.pm.trust+(Math.random()<.6?1:-1),10,80);toast('Media action deployed');save();render()},randomEvent:()=>{state.lastEventWeek=-99;maybeEvent();save();render()},
  pauseElection:()=>{if(state.election)state.election.speed=0;toast('Election night paused')},normalElection:()=>runElection(1),fastElection:()=>runElection(10),ultraElection:()=>runElection(50),finishElection:()=>finishElection()
};
window.reshuffle=i=>{const names=['Amelia Hart','Daniel Foster','Ravi Malik','Grace Turner','Noah Bennett','Imogen Clarke'];state.cabinet[i][0]=names[Math.floor(Math.random()*names.length)];state.cabinet[i][3]=clamp(state.cabinet[i][3]+10,20,95);state.cabinet[i][4]='Loyal';state.pm.unity=clamp(state.pm.unity+3,10,95);closeModal();save();render();toast('Reshuffle complete','Cabinet loyalty has improved.')};
window.createBill=()=>{const name=$('#billName').value.trim()||'New Bill';const cost=+$('#billCost').value;state.bills.unshift([name,'First Reading',1,6]);state.pm.politicalCapital=clamp(state.pm.politicalCapital-cost,0,100);closeModal();save();render();toast('Bill introduced',name)};
function startElectionNight(){if(state.election)return;const raw={};let remain=650;const poll=Object.entries(state.polling).sort((a,b)=>b[1]-a[1]);poll.forEach(([p,v],idx)=>{if(idx===poll.length-1){raw[p]=remain;return}const n=Math.max(0,Math.round(650*(v/100)*(0.8+Math.random()*.35)));raw[p]=Math.min(remain,n);remain-=raw[p]});state.election={exitPoll:raw,liveSeats:Object.fromEntries(Object.keys(raw).map(k=>[k,0])),declared:0,speed:1};state.declarations=[];toast('Polls closed','The exit poll is in. Election night has begun.')}
function runElection(count){if(!state.election)startElectionNight();for(let i=0;i<count&&state.election.declared<650;i++)declareSeat();save();render()}
function declareSeat(){const parties=Object.keys(state.election.exitPoll);const total=parties.reduce((s,p)=>s+state.election.liveSeats[p],0);let target=parties.map(p=>({p,need:state.election.exitPoll[p]-state.election.liveSeats[p]})).filter(x=>x.need>0).sort((a,b)=>b.need-a.need);const winner=(target[0]||{p:parties[Math.floor(Math.random()*parties.length)]}).p;state.election.liveSeats[winner]=(state.election.liveSeats[winner]||0)+1;state.election.declared++;const names=['Northfield','Rivermere','Eastborough','Kingswood','Seaton','Brampton','Westbridge','Southmere','Ashford Central','Newchester'];state.declarations.push([names[state.election.declared%names.length],`${winner} ${Math.random()<.25?'GAIN':'HOLD'}`,new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})])}
function finishElection(){if(!state.election)startElectionNight();state.election.liveSeats={...state.election.exitPoll};state.election.declared=650;state.seats={...state.election.exitPoll};const winner=Object.entries(state.seats).sort((a,b)=>b[1]-a[1])[0];modal('Election Complete',`<h2>${winner[0]}: ${winner[1]} seats</h2><p>${winner[1]>=326?'A majority government can be formed.':'No party has a majority. Government formation negotiations are required.'}</p><p>The result has been written into the simulation history.</p>`);state.history.unshift({date:state.date,title:'General Election',detail:`${winner[0]} won ${winner[1]} seats.`});state.electionWeeks=260;save();renderTop()}
render();
